### ISSUE TITLE
Turbowarp

### ISSUE THREAD

**Issue by yeetdragon24** [ego-lay-atman-bay/super-mario-maker-v6#1]
I found that by using a Chromebook to download the Turbowarp packager from the packager.turbowarp.org and using the `super mario maker v.6 v6.0.3.sb3` file, the file not only loaded but worked perfectly fine. However, selecting "turbowarp" on https://ego-lay-atman-bay.github.io/super-mario-maker-v6/ with a chromebook does not load properly. This may be due to an outdated version of the packager, or something else.

**Comment by ego-lay-atman-bay** [comment]
Sorry I didn't see this sooner. This issue has been fixed. I updated the packaged html file. I did also fix the project json so that it can load in htmlifier (before it couldn't load, because the turbowarp extension was in the json, even though I never used it). It might take a couple minutes to load, but it works.
